### ISSUE TITLE
Package worked, now fails to install on Julia 1.0

### ISSUE THREAD

**Issue by Kissaki** [oxinabox/MD5.jl#8]
I was using this package MD5 with Julia 1.0. That worked fine for a while.

Just now I used Pkg `up` to update packages, and MD5 failed. I removed the package. Now I can no longer install it. Did something change? I see no chances here, but the package requirements seem to have changed.

```
ERROR: Unsatisfiable requirements detected for package MD5 [6ac74813]:
 MD5 [6ac74813] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by oxinabox** [comment]
It got hit by the version cap.
Which was applied based on heuristic very recently.

I believe because the test fail on 1.0 because no `Base.Test` anymore.
Fixing now

**Comment by oxinabox** [comment]
Ah I see I forgot to merge #7 
once #7 is merged this will all be fine

**Comment by oxinabox** [comment]
Fixed now, you can run an update to get it
